version: '3.9'

services:
  postgres:
    image: postgres:14-alpine
    container_name: postgreDB
    restart: unless-stopped
    network_mode: "bridge"
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=S3cret
      - POSTGRES_USER=root
      - POSTGRES_DB=authDb
      - TZ='GMT+2'
      - PGTZ='GMT+2'

volumes:
  postgres_data:
    driver: local